spring.application.name=RideShare

# MongoDB Atlas connection
spring.data.mongodb.uri=mongodb+srv://sarthak6011:sarthakagarwal@notevault.apbgknc.mongodb.net/rideshare?retryWrites=true&w=majority

server.port=8080
